### ISSUE TITLE
show only one image

### ISSUE THREAD

**Issue by csae8092** [ofmgraz/ofm-static#17]
currently when going to a detail view of a book, all images of this book are loaded which is a lot of data
please have a look at what @cfhaak did in his project https://bundesverfassung-oesterreich.github.io/bv-static/bv_doc_id__19.html?prs=off&org=off&wrk=off&fs=default&img=on and implement the same logic i.e. when scrolling the text, the image adapts and the other way round

* please use opendseadragons default button as well as button layout
* try to reuse some code from @cfhaak 
* please work on this issue before engaging with https://github.com/ofmgraz/ofm-static/issues/16

**Comment by fsanzl** [comment]
OK, I am with it.

**Comment by fsanzl** [comment]
Solved
