### ISSUE TITLE
interactive map for listplace.html

### ISSUE THREAD

**Issue by csae8092** [ofmgraz/ofm-static#18]
https://ofmgraz.github.io/ofm-static/listplace.html

please consult with your colleagues your office on how to implement something like https://grocerist.github.io/grocerist-app/districts.html (@rausch-supola and @kisram) or https://nestroyca.acdh-dev.oeaw.ac.at/nestroyvienna/ (@cfhaak)

* a map with all places (having coordinates) in the table displayed
* if I filter the table, the map should only show the filtered results
* optional: the size of the pointer on the map should reflect how often the place is mentioned in the books

unlike the examples above I'd like to keep the table set up as it is, meaning the source for tabulator.js is a given HTML table and not some array of JSON-Objects (like above). If you come to a good solution I'd like to implement this solution in the dse-static-cookiecutter code base

@cfhaak if you have time next week it would be nice if you and @fsanzl could work on this one/two days focused on this issue
(because I want to copy paste your solution into emt.acdh-dev.oeaw.ac.at ;) )

**Comment by cfhaak** [comment]
@csae8092 I don't know for shure, but couldn't this be considered closed @fsanzl ?

**Comment by fsanzl** [comment]
I was addressing an issue with table formatting (not colored borders on top right and left), but I guess that, as the map is actually there, it's done. I'm closing it and will continue in a new issue.

**Comment by csae8092** [comment]
@fsanzl Please merge the code into main branch before opening a new issue

**Comment by fsanzl** [comment]
Merged
